name: Sincronizar Garmin com n8n

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script de extração
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          N8N_WEBHOOK: ${{ secrets.N8N_WEBHOOK }}
        run: python sync_treino.py
